In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('Indomaret_Stores_2019_08.csv')
x = dataset.iloc[:, [2,3]].values
y = dataset.iloc[:, -1].values

In [3]:
print(x)

[['grocery_or_supermarket' 'Tungkal IV Desa']
 ['convenience_store' 'Unnamed Road']
 ['convenience_store' 'Jl. R Sukamto Rt 27 Rw 07 8 Ilir Ilir Timur Ii']
 ...
 ['grocery_or_supermarket' 'Tanah Enam Ratus']
 ['supermarket' 'Jl. Mata Ie']
 ['grocery_or_supermarket' 'Batoh']]


In [4]:
print(y)

[240319 240320 240321 ... 257456 257457 257458]


In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.25, random_state=0)

In [6]:
print(x_train)

[['convenience_store' 'Jl. Radio Dalam No.14']
 ['convenience_store' 'Gedangan']
 ['convenience_store' 'Jl. Tengsaw No.No']
 ...
 ['convenience_store' 'Jl. Kartini']
 ['convenience_store' 'Jl. Marsma R. Iswahyudi No.72']
 ['convenience_store' 'Jl. Raya Leuwidamar']]


In [7]:
print(x_test)

[['grocery_or_supermarket' 'Jl. Raya Kaliabang Tengah No.3']
 ['convenience_store' 'Jl. Panca Usaha Blok De No 23 - Cakranegara']
 ['supermarket' 'JL. Yos Sudarso']
 ...
 ['grocery_or_supermarket' 'Kapal']
 ['supermarket' 'Bone Bone']
 ['convenience_store' 'Jl. KH Agus Salim']]


In [8]:
print(y_train)

[241947 248299 243499 ... 250164 251118 243051]


In [9]:
print(y_test)

[243678 251717 252917 ... 257269 252135 250826]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_train, y_train)

In [ ]:
y_pred = classifier.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [ ]:
from matplotlib.colors import ListedColormap
x_set, y_set = x_train, y_train
x1, x2 = np.meshgrid(np.arange(start = x_set[:, 0].min()-1, stop = x_set[:, 0].max() +1, step=0.01)),
                     np.arange(start = x_set[:, 1].min()-1, stop = x_set[:, 0].max() +1, step=0.01))
plt.contourf(x1,x2, classifier,predict(np.array([x1.ravel(), x2.ravel()].T).reshape(x1.shape),alpha = 0.75, cmap = ListedColormap(('red','green')))
plt.xlim(x1.min(), x1.max())
plt.xlim(x2.min(), x2.max())
for i, j in enumerate (np.unique(y_set)):
  plt.scatter(x_set[y_set == j, 0], x_set[y_set==j, 1],
              c = ListedColormap(('red','green'))(i), label = j) 
  plt.title('Klasifikasi Data dengan Naiive Bayes (Data Training)')
  plt.xlabel('Umur')
  plt.ylabel('Estimasi Gaji') 
  plt.legend()
  plt.show                   